language: r
sudo: false
cache: packages

matrix:
  include:
   - r: 3.2
   - r: 3.3
   - r: 3.4
   - r: 3.5
   - r: release
     before_cache:
       - Rscript -e 'remotes::install_cran("r-lib/pkgdown")'
       - Rscript -e 'remotes::install_github("r-lib/asciicast")'
     deploy:
       provider: script
       script: Rscript -e 'pkgdown::deploy_site_github()'
       skip_cleanup: true
       on:
         condition: $TRAVIS_BRANCH == "feature/pkgdown" || $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
     dist: xenial
     addons:
       apt:
         packages: libnode-dev
   - r: devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
